openapi: 3.0.3
info:
  title: Pokemon Collection API
  description: API endpoint for fetching Pokemon collection data
  version: 1.0.0

paths:
  /api/collection:
    get:
      summary: Get all Pokemon for collection view
      description: |
        Returns all Pokemon from the Source folder for display in the collection grid.
        Also returns available filter options (types and SR values) and user's starter status.
      security:
        - bearerAuth: []
      responses:
        '200':
          description: Successful response with Pokemon data
          content:
            application/json:
              schema:
                type: object
                required:
                  - success
                  - pokemon
                  - types
                  - srValues
                  - hasStarter
                properties:
                  success:
                    type: boolean
                    example: true
                  pokemon:
                    type: array
                    items:
                      $ref: '#/components/schemas/PokemonSummary'
                  types:
                    type: array
                    description: All available Pokemon types for filtering
                    items:
                      type: string
                    example: ["bug", "dark", "dragon", "electric", "fairy", "fighting", "fire", "flying", "ghost", "grass", "ground", "ice", "normal", "poison", "psychic", "rock", "steel", "water"]
                  srValues:
                    type: array
                    description: All unique SR values for filtering
                    items:
                      type: number
                    example: [0.125, 0.25, 0.5, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15]
                  hasStarter:
                    type: boolean
                    description: Whether the user has selected a starter Pokemon
                    example: true
        '401':
          description: Unauthorized - missing or invalid token
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '500':
          description: Server error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

  /api/collection/{pokemonId}:
    get:
      summary: Get detailed Pokemon information
      description: Returns complete Pokemon data for the detail modal
      security:
        - bearerAuth: []
      parameters:
        - name: pokemonId
          in: path
          required: true
          description: Pokemon ID (kebab-case identifier)
          schema:
            type: string
            example: "bulbasaur"
      responses:
        '200':
          description: Successful response with Pokemon details
          content:
            application/json:
              schema:
                type: object
                required:
                  - success
                  - pokemon
                properties:
                  success:
                    type: boolean
                    example: true
                  pokemon:
                    $ref: '#/components/schemas/PokemonDetail'
        '404':
          description: Pokemon not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT

  schemas:
    PokemonSummary:
      type: object
      description: Summary data for grid display
      required:
        - id
        - name
        - number
        - types
        - sr
        - spriteUrl
      properties:
        id:
          type: string
          description: Unique identifier
          example: "bulbasaur"
        name:
          type: string
          description: Display name
          example: "Bulbasaur"
        number:
          type: integer
          description: Pokedex number
          example: 1
        types:
          type: array
          items:
            type: string
          description: Pokemon types
          example: ["grass", "poison"]
        sr:
          type: number
          description: Spawn rate / rarity
          example: 0.5
        spriteUrl:
          type: string
          description: URL to sprite image
          example: "https://raw.githubusercontent.com/PokeAPI/sprites/..."

    PokemonDetail:
      type: object
      description: Complete Pokemon data for detail modal
      required:
        - id
        - name
        - number
        - types
        - sr
        - description
        - hp
        - ac
        - attributes
        - abilities
        - moves
        - media
      properties:
        id:
          type: string
          example: "bulbasaur"
        name:
          type: string
          example: "Bulbasaur"
        number:
          type: integer
          example: 1
        types:
          type: array
          items:
            type: string
          example: ["grass", "poison"]
        sr:
          type: number
          example: 0.5
        size:
          type: string
          example: "tiny"
        minLevel:
          type: integer
          example: 1
        description:
          type: string
          example: "The Seed Pokemon..."
        hp:
          type: integer
          example: 17
        ac:
          type: integer
          example: 13
        hitDice:
          type: string
          example: "d6"
        speed:
          type: array
          items:
            type: object
            properties:
              type:
                type: string
              value:
                type: integer
        attributes:
          type: object
          properties:
            str:
              type: integer
            dex:
              type: integer
            con:
              type: integer
            int:
              type: integer
            wis:
              type: integer
            cha:
              type: integer
        skills:
          type: array
          items:
            type: string
        savingThrows:
          type: array
          items:
            type: string
        abilities:
          type: array
          items:
            type: object
            properties:
              id:
                type: string
              hidden:
                type: boolean
              description:
                type: string
        moves:
          type: object
          properties:
            start:
              type: array
              items:
                type: string
            level2:
              type: array
              items:
                type: string
            tm:
              type: array
              items:
                type: integer
            egg:
              type: array
              items:
                type: string
        evolution:
          type: string
          example: "Stage 1 of 3"
        media:
          type: object
          properties:
            main:
              type: string
            sprite:
              type: string
            mainShiny:
              type: string
            spriteShiny:
              type: string

    Error:
      type: object
      required:
        - success
        - error
      properties:
        success:
          type: boolean
          example: false
        error:
          type: string
          example: "Error message description"
